openapi: 3.1.0
info:
  title: Announcement Service
  version: 1.0.0
tags:
  - name: Announcements
paths:
  /announcements:
    get:
      operationId: Announcements_list
      parameters:
        - name: sortByDateAsc
          in: query
          required: false
          description: |-
            日時昇順ソートするか

            降順ソートの場合はfalseを指定

            デフォルト値はtrue (昇順ソート)
          schema:
            type: boolean
          explode: false
        - name: filterIsActive
          in: query
          required: false
          description: |-
            公開状態で絞り込むか

            公開状態ではないもののみを抽出する場合はfalseを指定

            デフォルト値はnull (すべての公開状態を含む)
          schema:
            type: boolean
          explode: false
      responses:
        '200':
          description: おしらせのリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announcement'
      tags:
        - Announcements
components:
  schemas:
    Announcement:
      type: object
      required:
        - id
        - title
        - date
        - url
        - isActive
      properties:
        id:
          type: string
        title:
          type: string
        date:
          type: string
          format: date-time
        url:
          type: string
          format: uri
        isActive:
          type: boolean
servers:
  - url: http://localhost:8080
    description: Local
    variables: {}
  - url: https://announcement-api-dev-107577467292.asia-northeast1.run.app
    description: Development
    variables: {}
  - url: https://announcement-api-stg-107577467292.asia-northeast1.run.app
    description: Staging
    variables: {}
  - url: https://announcement-api-qa-107577467292.asia-northeast1.run.app
    description: QA
    variables: {}
  - url: https://announcement-api-107577467292.asia-northeast1.run.app
    description: Production
    variables: {}
